<?php
$page_title    = 'Invoice Details';
$page_subtitle = 'View & Manage Invoice';
require_once __DIR__ . '/../../includes/acc_header.php';

$invoice_id = (int)($_GET['invoice_id'] ?? 0);
if (!$invoice_id) {
    header('Location: acc_invoices.php');
    exit();
}

$msg_success = '';
$msg_error   = '';

// ── Handle POST actions ────────────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    // ── GENERATE INVOICE (convert quotation → invoice) ─────────────────────────
    if ($action === 'generate_invoice') {
        $due_date = mysqli_real_escape_string($conn, $_POST['due_date'] ?? '');
        $notes    = mysqli_real_escape_string($conn, $_POST['notes'] ?? '');

        // Validate it's a quotation linked to a client-approved fault
        $chk = mysqli_query($conn, "
            SELECT i.*, c.COMPANY_NAME, c.COMPANY_EMAIL, c.CLIENT_ID,
                   rf.REP_FAULT_ID, rf.STATUS as FAULT_STATUS
            FROM invoice i
            LEFT JOIN client c ON i.CLIENT_ID = c.CLIENT_ID
            LEFT JOIN assignment a ON i.ASSIGN_ID = a.ASSIGN_ID
            LEFT JOIN reported_fault rf ON a.REP_FAULT_ID = rf.REP_FAULT_ID
            WHERE i.INVOICE_ID = $invoice_id AND i.TYPE = 'Quotation'
        ");

        if (!$chk || mysqli_num_rows($chk) === 0) {
            $msg_error = 'This record is not a valid quotation or has already been converted.';
        } elseif (empty($due_date)) {
            $msg_error = 'Please set a payment due date.';
        } else {
            $q = mysqli_fetch_assoc($chk);
            $today = date('Y-m-d');

            // Convert quotation → invoice
            $upd = mysqli_query($conn, "
                UPDATE invoice SET
                    TYPE         = 'Invoice',
                    STATUS       = 'Pending Payment',
                    INVOICE_DATE = '$today',
                    DUE_DATE     = '$due_date'
                WHERE INVOICE_ID = $invoice_id
            ");

            if ($upd) {
                // Audit trail
                mysqli_query($conn, "
                    INSERT INTO invoice_tracking (invoice_id, action, description, performed_by_id, performed_by_role)
                    VALUES ($invoice_id, 'Invoice Generated',
                        'Invoice generated by accountant from quotation. Due: $due_date. Notes: $notes',
                        $acc_id, 'Accountant')
                ");

                // Notify client
                $cid     = (int)$q['CLIENT_ID'];
                $total   = number_format($q['TOTAL'], 2);
                $inv_num = 'INV-' . str_pad($invoice_id, 4, '0', STR_PAD_LEFT);
                mysqli_query($conn, "
                    INSERT INTO notifications (user_id, user_type, title, message)
                    VALUES ($cid, 'Client',
                        'Invoice Ready – $inv_num',
                        'Your invoice $inv_num for E$total is due on $due_date. Please make payment in the Invoices & Payments section.')
                ");

                // Notify admin
                mysqli_query($conn, "
                    INSERT INTO notifications (user_id, user_type, title, message)
                    VALUES (1, 'Admin',
                        'Invoice Generated – $inv_num',
                        'Accountant generated invoice $inv_num (E$total) for fault #" . (int)($q['REP_FAULT_ID'] ?? 0) . ". Due: $due_date.')
                ");

                $msg_success = "Invoice $inv_num generated successfully! Client has been notified.";
            } else {
                $msg_error = 'Database error: ' . mysqli_error($conn);
            }
        }
    }

    // ── SEND / RESEND INVOICE NOTIFICATION TO CLIENT ───────────────────────────
    if ($action === 'send_to_client') {
        $chk = mysqli_query($conn, "
            SELECT i.*, c.COMPANY_NAME, c.CLIENT_ID
            FROM invoice i
            LEFT JOIN client c ON i.CLIENT_ID = c.CLIENT_ID
            WHERE i.INVOICE_ID = $invoice_id AND i.TYPE = 'Invoice'
        ");

        if (!$chk || mysqli_num_rows($chk) === 0) {
            $msg_error = 'Invoice must be generated before it can be sent. Please generate the invoice first.';
        } else {
            $inv      = mysqli_fetch_assoc($chk);
            $cid      = (int)$inv['CLIENT_ID'];
            $total    = number_format($inv['TOTAL'], 2);
            $inv_num  = 'INV-' . str_pad($invoice_id, 4, '0', STR_PAD_LEFT);
            $due      = $inv['DUE_DATE'] ? date('d M Y', strtotime($inv['DUE_DATE'])) : 'N/A';

            mysqli_query($conn, "
                INSERT INTO notifications (user_id, user_type, title, message)
                VALUES ($cid, 'Client',
                    'Invoice Reminder – $inv_num',
                    'Reminder: Invoice $inv_num for E$total is due on $due. Please log in to make payment.')
            ");

            // Also log this action
            mysqli_query($conn, "
                INSERT INTO invoice_tracking (invoice_id, action, description, performed_by_id, performed_by_role)
                VALUES ($invoice_id, 'Invoice Sent', 'Invoice reminder sent to client by accountant', $acc_id, 'Accountant')
            ");

            $msg_success = "Invoice reminder sent to client successfully.";
        }
    }
}

// ── Load invoice/quotation record ─────────────────────────────────────────────
$inv_q = mysqli_query($conn, "
    SELECT i.*,
           c.COMPANY_NAME, c.COMPANY_EMAIL, c.COMPANY_PHONE, c.COMPANY_ADDRESS,
           c.CONTACT_PERSON_NAME, c.CLIENT_ID,
           rf.REP_FAULT_ID, rf.DESCRIPTION as FAULT_DESC, rf.STATUS as FAULT_STATUS,
           rf.PRIORITY, rf.REPORT_DATE, rf.REPORTED_BY,
           a.ASSIGN_ID, a.ASSIGN_DATE, a.DUE_DATE as ASSIGN_DUE,
           GROUP_CONCAT(DISTINCT e.FULL_NAME ORDER BY e.FULL_NAME SEPARATOR ', ') as TECHNICIANS
    FROM invoice i
    LEFT JOIN client c           ON i.CLIENT_ID  = c.CLIENT_ID
    LEFT JOIN assignment a       ON i.ASSIGN_ID  = a.ASSIGN_ID
    LEFT JOIN reported_fault rf  ON a.REP_FAULT_ID = rf.REP_FAULT_ID
    LEFT JOIN assignment_technician at2 ON a.ASSIGN_ID = at2.ASSIGN_ID
    LEFT JOIN employee e         ON at2.EMP_ID   = e.EMP_ID
    WHERE i.INVOICE_ID = $invoice_id
    GROUP BY i.INVOICE_ID
");

if (!$inv_q || mysqli_num_rows($inv_q) === 0) {
    echo '<div class="page-content"><div class="alert alert-danger"><i class="ti ti-alert-circle"></i> Invoice #' . $invoice_id . ' not found.</div></div>';
    require_once '../../includes/acc_footer.php';
    exit();
}

$inv = mysqli_fetch_assoc($inv_q);

// ── Line items ────────────────────────────────────────────────────────────────
$lines_q = mysqli_query($conn, "
    SELECT * FROM invoice_line WHERE INVOICE_ID = $invoice_id ORDER BY LINE_ID
");
$lines = [];
while ($l = mysqli_fetch_assoc($lines_q)) $lines[] = $l;

// ── Payments for this invoice ─────────────────────────────────────────────────
$pays_q = mysqli_query($conn, "
    SELECT p.*, r.RECEIPT_ID, r.RECEIPT_DATE
    FROM payment p
    LEFT JOIN receipt r ON r.PAYMENT_ID = p.PAYMENT_ID
    WHERE p.INVOICE_ID = $invoice_id
    ORDER BY p.PAYMENT_DATE DESC
");
$payments = [];
while ($p = mysqli_fetch_assoc($pays_q)) $payments[] = $p;

// ── Audit trail ───────────────────────────────────────────────────────────────
$track_q = mysqli_query($conn, "
    SELECT it.*, e.FULL_NAME
    FROM invoice_tracking it
    LEFT JOIN employee e ON e.EMP_ID = it.performed_by_id
    WHERE it.invoice_id = $invoice_id
    ORDER BY it.created_at ASC
");
$tracking = [];
while ($t = mysqli_fetch_assoc($track_q)) $tracking[] = $t;

// ── Client confirmation ───────────────────────────────────────────────────────
$cc_q = mysqli_query($conn, "
    SELECT * FROM client_confirmations
    WHERE fault_id = " . (int)($inv['REP_FAULT_ID'] ?? 0) . "
    AND client_id = " . (int)($inv['CLIENT_ID'] ?? 0)
);
$client_confirm = ($cc_q && mysqli_num_rows($cc_q) > 0) ? mysqli_fetch_assoc($cc_q) : null;

// ── Helpers ───────────────────────────────────────────────────────────────────
$is_quotation = ($inv['TYPE'] === 'Quotation');
$is_invoice   = ($inv['TYPE'] === 'Invoice');
$status       = $inv['STATUS'] ?? '';
$total_paid   = array_sum(array_map(fn($p) => $p['STATUS'] === 'Verified' ? (float)$p['AMOUNT_PAID'] : 0, $payments));
$balance_due  = (float)$inv['TOTAL'] - $total_paid;
$inv_num      = ($is_invoice ? 'INV-' : 'QUO-') . str_pad($invoice_id, 4, '0', STR_PAD_LEFT);
$client_approved = ($client_confirm && $client_confirm['confirmation_status'] === 'Confirmed');
$can_generate = $is_quotation && $client_approved;
$is_overdue   = $is_invoice && $inv['DUE_DATE'] && $inv['DUE_DATE'] < date('Y-m-d') && $status !== 'Paid';

// Fault description parser
function parseFaultField(string $raw, string $key): string {
    if (preg_match('/' . preg_quote($key, '/') . ':\s*(.+)/i', $raw, $m)) return trim($m[1]);
    return '';
}
$fault_desc    = $inv['FAULT_DESC'] ?? '';
$fault_title   = parseFaultField($fault_desc, 'FAULT TITLE') ?: mb_strimwidth(explode("\n", $fault_desc)[0], 0, 70, '…');
$fault_ref     = parseFaultField($fault_desc, 'FAULT REFERENCE') ?: ('BQ-' . str_pad($inv['REP_FAULT_ID'] ?? 0, 5, '0', STR_PAD_LEFT));
$fault_cat     = parseFaultField($fault_desc, 'CATEGORY') ?: 'General';
$fault_equip   = parseFaultField($fault_desc, 'EQUIPMENT TYPE');
?>

<style>
/* ── Invoice sheet ──────────────────────────────────────── */
.inv-sheet {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 14px;
    overflow: hidden;
}
.inv-sheet-header {
    background: linear-gradient(135deg, #1a2030 0%, #0d1117 100%);
    border-bottom: 2px solid var(--accent);
    padding: 2rem;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 1rem;
    flex-wrap: wrap;
}
.inv-logo { font-size: 1.6rem; font-weight: 800; color: var(--accent); letter-spacing: -.5px; }
.inv-logo span { color: var(--text); }
.inv-logo small { display: block; font-size: .7rem; font-weight: 400; color: var(--text2); letter-spacing: 1.5px; text-transform: uppercase; margin-top: .2rem; }
.inv-meta-block { text-align: right; }
.inv-meta-block .inv-number { font-size: 1.3rem; font-weight: 800; color: var(--text); }
.inv-meta-block .inv-type-pill {
    display: inline-block;
    padding: .2rem .8rem;
    border-radius: 20px;
    font-size: .75rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: .05em;
    margin-bottom: .5rem;
}
.inv-meta-block .inv-type-pill.invoice { background: rgba(63,185,80,.2); color: var(--success); border: 1px solid rgba(63,185,80,.3); }
.inv-meta-block .inv-type-pill.quotation { background: rgba(240,165,0,.2); color: var(--accent); border: 1px solid rgba(240,165,0,.3); }
.inv-meta-row { font-size: .8rem; color: var(--text2); margin-top: .25rem; }
.inv-meta-row strong { color: var(--text); }

.inv-parties {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1px;
    background: var(--border);
    border-bottom: 1px solid var(--border);
}
.inv-party {
    background: var(--surface);
    padding: 1.25rem 2rem;
}
.inv-party .party-label { font-size: .68rem; font-weight: 700; text-transform: uppercase; letter-spacing: .1em; color: var(--text2); margin-bottom: .5rem; }
.inv-party .party-name { font-size: 1rem; font-weight: 700; color: var(--text); margin-bottom: .3rem; }
.inv-party .party-detail { font-size: .8rem; color: var(--text2); line-height: 1.6; }

.inv-fault-bar {
    background: rgba(240,165,0,.06);
    border-bottom: 1px solid rgba(240,165,0,.15);
    padding: .85rem 2rem;
    display: flex;
    align-items: center;
    gap: 1.5rem;
    flex-wrap: wrap;
    font-size: .82rem;
}
.inv-fault-bar .fbar-item { display: flex; align-items: center; gap: .4rem; color: var(--text2); }
.inv-fault-bar .fbar-item strong { color: var(--text); }
.inv-fault-bar .fbar-item i { color: var(--accent); font-size: .9rem; }

.inv-lines-section { padding: 1.5rem 2rem; }
.inv-lines-section h3 { font-size: .8rem; font-weight: 700; text-transform: uppercase; letter-spacing: .08em; color: var(--text2); margin-bottom: 1rem; display: flex; align-items: center; gap: .5rem; }
.inv-lines-section h3::after { content: ''; flex: 1; height: 1px; background: var(--border); }

.lines-table { width: 100%; border-collapse: collapse; font-size: .875rem; }
.lines-table thead tr { background: rgba(240,165,0,.08); }
.lines-table th { padding: .65rem 1rem; text-align: left; font-size: .72rem; font-weight: 700; text-transform: uppercase; letter-spacing: .06em; color: var(--accent); border-bottom: 1px solid rgba(240,165,0,.2); }
.lines-table th:not(:first-child) { text-align: right; }
.lines-table td { padding: .85rem 1rem; border-bottom: 1px solid var(--border); color: var(--text); vertical-align: middle; }
.lines-table td:not(:first-child) { text-align: right; }
.lines-table tbody tr:last-child td { border-bottom: none; }
.lines-table .total-row td { background: rgba(240,165,0,.06); font-weight: 700; color: var(--accent); border-top: 2px solid rgba(240,165,0,.3); font-size: 1rem; }

.inv-summary-bar {
    margin: 0 2rem 1.5rem;
    display: flex;
    justify-content: flex-end;
    gap: 0;
}
.summary-box {
    background: var(--surface2);
    border: 1px solid var(--border);
    padding: 1rem 1.5rem;
    min-width: 180px;
    text-align: right;
}
.summary-box:first-child { border-radius: 10px 0 0 10px; }
.summary-box:last-child  { border-radius: 0 10px 10px 0; }
.summary-box + .summary-box { border-left: none; }
.summary-box .sb-label { font-size: .72rem; color: var(--text2); text-transform: uppercase; letter-spacing: .06em; font-weight: 600; margin-bottom: .3rem; }
.summary-box .sb-val { font-size: 1.2rem; font-weight: 800; color: var(--text); }
.summary-box.highlight { background: rgba(240,165,0,.08); border-color: rgba(240,165,0,.3); }
.summary-box.highlight .sb-val { color: var(--accent); font-size: 1.6rem; }
.summary-box.paid-box .sb-val { color: var(--success); }
.summary-box.balance-box .sb-val { color: <?= $balance_due > 0 ? 'var(--danger)' : 'var(--success)' ?>; }

/* ── Status banner ──────────────────────────────────────── */
.status-banner-bar {
    margin: 1rem 2rem;
    padding: .85rem 1.25rem;
    border-radius: 10px;
    display: flex;
    align-items: center;
    gap: .75rem;
    font-size: .875rem;
    font-weight: 500;
}
.status-banner-bar.pending   { background: rgba(210,153,34,.1); border: 1px solid rgba(210,153,34,.3); color: var(--warning); }
.status-banner-bar.paid      { background: rgba(63,185,80,.1); border: 1px solid rgba(63,185,80,.3); color: var(--success); }
.status-banner-bar.overdue   { background: rgba(248,81,73,.1); border: 1px solid rgba(248,81,73,.3); color: var(--danger); }
.status-banner-bar.quotation { background: rgba(240,165,0,.1); border: 1px solid rgba(240,165,0,.3); color: var(--accent); }
.status-banner-bar.approved  { background: rgba(63,185,80,.08); border: 1px solid rgba(63,185,80,.2); color: var(--success); }

/* ── Action buttons section ─────────────────────────────── */
.actions-panel {
    background: var(--surface2);
    border: 1px solid var(--border);
    border-radius: 12px;
    padding: 1.25rem;
    margin-bottom: 1.25rem;
}
.actions-panel h3 { font-size: .85rem; font-weight: 700; color: var(--text); margin-bottom: 1rem; display: flex; align-items: center; gap: .5rem; }

.generate-form { display: flex; flex-direction: column; gap: .85rem; }
.generate-form .form-row { display: grid; grid-template-columns: 1fr 1fr; gap: .75rem; }

/* ── Payments ────────────────────────────────────────────── */
.payment-card {
    background: var(--surface2);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 1rem 1.25rem;
    margin-bottom: .6rem;
    display: flex;
    align-items: center;
    gap: 1rem;
    flex-wrap: wrap;
}
.pay-icon { width: 40px; height: 40px; border-radius: 10px; display: flex; align-items: center; justify-content: center; font-size: 1.1rem; flex-shrink: 0; }
.pay-icon.verified  { background: rgba(63,185,80,.15); color: var(--success); }
.pay-icon.pending   { background: rgba(210,153,34,.15); color: var(--warning); }
.pay-icon.rejected  { background: rgba(248,81,73,.15); color: var(--danger); }

/* ── Timeline ───────────────────────────────────────────── */
.timeline-item { display: flex; gap: 1rem; padding-bottom: 1rem; position: relative; }
.timeline-item:last-child { padding-bottom: 0; }
.tl-dot { width: 30px; height: 30px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: .85rem; flex-shrink: 0; border: 2px solid var(--border); background: var(--surface2); }
.tl-line { position: absolute; left: 14px; top: 30px; bottom: 0; width: 2px; background: var(--border); }
.timeline-item:last-child .tl-line { display: none; }
.tl-body { flex: 1; padding-top: .3rem; }
.tl-action { font-size: .85rem; font-weight: 600; color: var(--text); }
.tl-desc { font-size: .78rem; color: var(--text2); margin-top: .2rem; line-height: 1.5; }
.tl-time { font-size: .72rem; color: var(--text2); margin-top: .3rem; }

/* ── Print ──────────────────────────────────────────────── */
@media print {
    .sidebar, .topbar, .actions-panel, .back-link, .no-print { display: none !important; }
    .main { margin-left: 0 !important; }
    .inv-sheet { border: none; box-shadow: none; }
    body { background: #fff; color: #000; }
}

@media (max-width: 700px) {
    .inv-parties { grid-template-columns: 1fr; }
    .generate-form .form-row { grid-template-columns: 1fr; }
    .inv-sheet-header { flex-direction: column; }
    .inv-meta-block { text-align: left; }
}
</style>

<!-- Back link -->
<div class="back-link no-print" style="margin-bottom:1rem">
    <a href="<?= $is_quotation ? 'generate_invoice.php' : 'acc_invoices.php' ?>" class="btn btn-secondary btn-sm">
        <i class="ti ti-arrow-left"></i> Back to <?= $is_quotation ? 'Generate Invoice' : 'All Invoices' ?>
    </a>
    <a href="generate_invoice.php" class="btn btn-secondary btn-sm" style="margin-left:.5rem">
        <i class="ti ti-file-text"></i> Generate Invoice
    </a>
</div>

<?php if ($msg_success): ?>
<div class="alert alert-success"><i class="ti ti-circle-check"></i> <?= htmlspecialchars($msg_success) ?></div>
<?php endif; ?>
<?php if ($msg_error): ?>
<div class="alert alert-danger"><i class="ti ti-alert-circle"></i> <?= htmlspecialchars($msg_error) ?></div>
<?php endif; ?>

<div style="display:grid;grid-template-columns:1fr 340px;gap:1.25rem;align-items:flex-start">

<!-- ══ LEFT: Invoice Sheet ══════════════════════════════════════════════════════ -->
<div>

    <!-- ── ACTIONS PANEL ── -->
    <div class="actions-panel no-print">
        <h3><i class="ti ti-tool" style="color:var(--accent)"></i> Actions</h3>
        <div style="display:flex;gap:.75rem;flex-wrap:wrap;align-items:center">

            <?php if ($can_generate): ?>
            <!-- GENERATE INVOICE BUTTON → shows modal -->
            <button class="btn btn-primary" onclick="document.getElementById('generateModal').style.display='flex'">
                <i class="ti ti-file-check"></i> Generate Invoice
            </button>
            <?php elseif ($is_quotation && !$client_approved): ?>
            <div class="alert alert-warning" style="margin:0;padding:.5rem .85rem;font-size:.82rem">
                <i class="ti ti-info-circle"></i> Waiting for client to approve the completed work before invoice can be generated.
            </div>
            <?php endif; ?>

            <?php if ($is_invoice): ?>
            <!-- SEND TO CLIENT BUTTON -->
            <form method="POST" style="display:inline">
                <input type="hidden" name="action" value="send_to_client">
                <button type="submit" class="btn btn-info" onclick="return confirm('Send invoice reminder notification to client?')">
                    <i class="ti ti-send"></i> Send to Client
                </button>
            </form>
            <?php endif; ?>

            <!-- PRINT -->
            <button class="btn btn-secondary" onclick="window.print()">
                <i class="ti ti-printer"></i> Print / PDF
            </button>

            <!-- VIEW ALL INVOICES -->
            <a href="acc_invoices.php" class="btn btn-secondary">
                <i class="ti ti-receipt"></i> All Invoices
            </a>
        </div>
    </div>

    <!-- ── INVOICE SHEET ── -->
    <div class="inv-sheet" id="printable">

        <!-- Header -->
        <div class="inv-sheet-header">
            <div>
                <div class="inv-logo">Busi<span>quip</span>
                    <small>Eswatini · Technical Services</small>
                </div>
                <div style="font-size:.8rem;color:var(--text2);margin-top:.75rem;line-height:1.7">
                    <i class="ti ti-map-pin" style="color:var(--accent);font-size:.85rem"></i> Mbabane, Hhohho, Eswatini<br>
                    <i class="ti ti-mail" style="color:var(--accent);font-size:.85rem"></i> finance@busiquip.com<br>
                    <i class="ti ti-world" style="color:var(--accent);font-size:.85rem"></i> www.busiquip.com
                </div>
            </div>
            <div class="inv-meta-block">
                <div>
                    <span class="inv-type-pill <?= $is_invoice ? 'invoice' : 'quotation' ?>">
                        <?= $is_invoice ? 'Invoice' : 'Quotation' ?>
                    </span>
                </div>
                <div class="inv-number"><?= $inv_num ?></div>
                <?php if ($is_overdue): ?>
                <div style="display:inline-block;padding:.2rem .6rem;background:rgba(248,81,73,.2);border:1px solid rgba(248,81,73,.4);border-radius:6px;font-size:.7rem;color:var(--danger);font-weight:700;margin-top:.3rem">
                    OVERDUE
                </div>
                <?php endif; ?>
                <div class="inv-meta-row" style="margin-top:.5rem">
                    <strong>Date:</strong> <?= $inv['INVOICE_DATE'] ? date('d M Y', strtotime($inv['INVOICE_DATE'])) : date('d M Y') ?>
                </div>
                <?php if ($inv['DUE_DATE']): ?>
                <div class="inv-meta-row">
                    <strong>Due:</strong>
                    <span style="color:<?= $is_overdue ? 'var(--danger)' : 'var(--text)' ?>">
                        <?= date('d M Y', strtotime($inv['DUE_DATE'])) ?>
                    </span>
                </div>
                <?php endif; ?>
                <div class="inv-meta-row" style="margin-top:.5rem">
                    <?php
                    $sb = ['Paid'=>'badge-paid','Pending Payment'=>'badge-pending','Submitted'=>'badge-submitted'];
                    $sc = $sb[$status] ?? 'badge-cancelled';
                    ?>
                    <span class="badge <?= $sc ?>"><?= htmlspecialchars($status ?: 'Draft') ?></span>
                </div>
            </div>
        </div>

        <!-- Parties -->
        <div class="inv-parties">
            <div class="inv-party">
                <div class="party-label">From</div>
                <div class="party-name">BUSIQUIP ESWATINI</div>
                <div class="party-detail">
                    Technical Fault Management Services<br>
                    Mbabane, Hhohho Region<br>
                    Kingdom of Eswatini<br>
                    finance@busiquip.com
                </div>
            </div>
            <div class="inv-party">
                <div class="party-label">Bill To</div>
                <div class="party-name"><?= htmlspecialchars($inv['COMPANY_NAME'] ?? 'Unknown Client') ?></div>
                <div class="party-detail">
                    <?php if ($inv['CONTACT_PERSON_NAME']): ?>
                    Attn: <?= htmlspecialchars($inv['CONTACT_PERSON_NAME']) ?><br>
                    <?php endif; ?>
                    <?php if ($inv['COMPANY_ADDRESS']): ?>
                    <?= htmlspecialchars($inv['COMPANY_ADDRESS']) ?><br>
                    <?php endif; ?>
                    <?php if ($inv['COMPANY_EMAIL']): ?>
                    <?= htmlspecialchars($inv['COMPANY_EMAIL']) ?><br>
                    <?php endif; ?>
                    <?php if ($inv['COMPANY_PHONE']): ?>
                    <?= htmlspecialchars($inv['COMPANY_PHONE']) ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <!-- Fault reference bar -->
        <?php if ($inv['REP_FAULT_ID']): ?>
        <div class="inv-fault-bar">
            <div class="fbar-item">
                <i class="ti ti-alert-circle"></i>
                <span>Fault Ref: <strong><?= htmlspecialchars($fault_ref) ?></strong></span>
            </div>
            <div class="fbar-item">
                <i class="ti ti-tag"></i>
                <span>Category: <strong><?= htmlspecialchars($fault_cat) ?></strong></span>
            </div>
            <?php if ($fault_equip): ?>
            <div class="fbar-item">
                <i class="ti ti-device-desktop"></i>
                <span>Equipment: <strong><?= htmlspecialchars($fault_equip) ?></strong></span>
            </div>
            <?php endif; ?>
            <?php if ($inv['TECHNICIANS']): ?>
            <div class="fbar-item">
                <i class="ti ti-user-check"></i>
                <span>Technician: <strong><?= htmlspecialchars($inv['TECHNICIANS']) ?></strong></span>
            </div>
            <?php endif; ?>
            <?php if ($inv['PRIORITY']): ?>
            <div class="fbar-item">
                <i class="ti ti-flag"></i>
                <span>Priority: <strong><?= htmlspecialchars($inv['PRIORITY']) ?></strong></span>
            </div>
            <?php endif; ?>
        </div>
        <?php endif; ?>

        <!-- Status banner inside sheet -->
        <?php if ($is_overdue): ?>
        <div class="status-banner-bar overdue" style="margin:1rem 2rem 0">
            <i class="ti ti-alert-triangle" style="font-size:1.1rem"></i>
            This invoice is <strong style="margin:0 .3rem">overdue</strong> since <?= date('d M Y', strtotime($inv['DUE_DATE'])) ?>. Please follow up with the client.
        </div>
        <?php elseif ($status === 'Paid'): ?>
        <div class="status-banner-bar paid" style="margin:1rem 2rem 0">
            <i class="ti ti-circle-check" style="font-size:1.1rem"></i>
            <strong>Paid in full.</strong> &nbsp;This invoice has been settled.
        </div>
        <?php elseif ($status === 'Pending Payment' && $is_invoice): ?>
        <div class="status-banner-bar pending" style="margin:1rem 2rem 0">
            <i class="ti ti-hourglass" style="font-size:1.1rem"></i>
            Awaiting client payment. Due: <strong style="margin-left:.3rem"><?= $inv['DUE_DATE'] ? date('d M Y', strtotime($inv['DUE_DATE'])) : 'N/A' ?></strong>
        </div>
        <?php elseif ($is_quotation && $client_approved): ?>
        <div class="status-banner-bar approved" style="margin:1rem 2rem 0">
            <i class="ti ti-circle-check" style="font-size:1.1rem"></i>
            Client has <strong style="margin:0 .3rem">approved</strong> the completed work. Ready to generate invoice.
        </div>
        <?php elseif ($is_quotation): ?>
        <div class="status-banner-bar quotation" style="margin:1rem 2rem 0">
            <i class="ti ti-file-invoice" style="font-size:1.1rem"></i>
            This is a <strong style="margin:0 .3rem">quotation</strong>. It will be converted to an invoice after client approval.
        </div>
        <?php endif; ?>

        <!-- Line items -->
        <div class="inv-lines-section">
            <h3><i class="ti ti-list" style="color:var(--accent)"></i> Services & Charges</h3>
            <?php if (empty($lines)): ?>
                <div class="empty-state" style="padding:1.5rem"><i class="ti ti-inbox"></i><p>No line items found.</p></div>
            <?php else: ?>
            <div style="overflow-x:auto;border-radius:8px;border:1px solid var(--border)">
                <table class="lines-table">
                    <thead>
                        <tr>
                            <th style="width:50%">Description</th>
                            <th>Qty</th>
                            <th>Unit Price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($lines as $line): ?>
                        <tr>
                            <td><?= htmlspecialchars($line['DESCRIPTION'] ?? '—') ?></td>
                            <td><?= htmlspecialchars($line['QUANTITY'] ?? 1) ?></td>
                            <td>E <?= number_format((float)$line['UNIT_PRICE'], 2) ?></td>
                            <td>E <?= number_format((float)$line['LINE_TOTAL'], 2) ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                    <tfoot>
                        <tr class="total-row">
                            <td colspan="3"><i class="ti ti-receipt"></i> TOTAL AMOUNT</td>
                            <td>E <?= number_format((float)$inv['TOTAL'], 2) ?></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <?php endif; ?>
        </div>

        <!-- Summary boxes -->
        <div class="inv-summary-bar">
            <div class="summary-box">
                <div class="sb-label">Subtotal</div>
                <div class="sb-val">E <?= number_format((float)$inv['TOTAL'], 2) ?></div>
            </div>
            <?php if ($total_paid > 0): ?>
            <div class="summary-box paid-box">
                <div class="sb-label">Amount Paid</div>
                <div class="sb-val">E <?= number_format($total_paid, 2) ?></div>
            </div>
            <div class="summary-box balance-box">
                <div class="sb-label">Balance Due</div>
                <div class="sb-val">E <?= number_format(max(0, $balance_due), 2) ?></div>
            </div>
            <?php else: ?>
            <div class="summary-box highlight">
                <div class="sb-label">Total Due</div>
                <div class="sb-val">E <?= number_format((float)$inv['TOTAL'], 2) ?></div>
            </div>
            <?php endif; ?>
        </div>

        <!-- Payment terms footer in sheet -->
        <div style="padding:1rem 2rem 2rem;border-top:1px solid var(--border)">
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;font-size:.8rem;color:var(--text2)">
                <div>
                    <div style="font-weight:700;color:var(--text);margin-bottom:.4rem">Payment Methods</div>
                    <div>• Mobile Money (ESwatini Mobile)</div>
                    <div>• Bank Transfer (Standard Bank / FNB)</div>
                    <div>• Card Transfer</div>
                    <div style="margin-top:.5rem;font-size:.72rem">Late payments incur 1.5% monthly finance charge.</div>
                </div>
                <div>
                    <div style="font-weight:700;color:var(--text);margin-bottom:.4rem">Bank Details</div>
                    <div>Account: BUSIQUIP ESWATINI</div>
                    <div>Branch: Mbabane Main</div>
                    <div>Ref: <?= $inv_num ?></div>
                </div>
            </div>
        </div>

    </div><!-- /.inv-sheet -->
</div><!-- /.left -->

<!-- ══ RIGHT: Sidebar panels ════════════════════════════════════════════════════ -->
<div style="display:flex;flex-direction:column;gap:1.25rem">

    <!-- Invoice Status Card -->
    <div class="card">
        <div class="card-title"><i class="ti ti-info-circle" style="color:var(--accent)"></i> Invoice Status</div>
        <div style="display:flex;flex-direction:column;gap:.65rem;font-size:.85rem">
            <div style="display:flex;justify-content:space-between;align-items:center">
                <span style="color:var(--text2)">Document Type</span>
                <span class="badge <?= $is_invoice ? 'badge-paid' : 'badge-submitted' ?>"><?= $inv['TYPE'] ?></span>
            </div>
            <div style="display:flex;justify-content:space-between;align-items:center">
                <span style="color:var(--text2)">Status</span>
                <span class="badge <?= $sc ?>"><?= htmlspecialchars($status ?: 'Draft') ?></span>
            </div>
            <div style="display:flex;justify-content:space-between;align-items:center">
                <span style="color:var(--text2)">Total Amount</span>
                <strong style="color:var(--accent)">E <?= number_format((float)$inv['TOTAL'], 2) ?></strong>
            </div>
            <?php if ($total_paid > 0): ?>
            <div style="display:flex;justify-content:space-between;align-items:center">
                <span style="color:var(--text2)">Paid</span>
                <strong style="color:var(--success)">E <?= number_format($total_paid, 2) ?></strong>
            </div>
            <div style="display:flex;justify-content:space-between;align-items:center;padding-top:.5rem;border-top:1px solid var(--border)">
                <span style="color:var(--text2)">Balance Due</span>
                <strong style="color:<?= $balance_due > 0 ? 'var(--danger)' : 'var(--success)' ?>">
                    E <?= number_format(max(0, $balance_due), 2) ?>
                </strong>
            </div>
            <?php endif; ?>
            <?php if ($inv['INVOICE_DATE']): ?>
            <div style="display:flex;justify-content:space-between">
                <span style="color:var(--text2)">Invoice Date</span>
                <span><?= date('d M Y', strtotime($inv['INVOICE_DATE'])) ?></span>
            </div>
            <?php endif; ?>
            <?php if ($inv['DUE_DATE']): ?>
            <div style="display:flex;justify-content:space-between">
                <span style="color:var(--text2)">Due Date</span>
                <span style="color:<?= $is_overdue ? 'var(--danger)' : 'var(--text)' ?>"><?= date('d M Y', strtotime($inv['DUE_DATE'])) ?></span>
            </div>
            <?php endif; ?>
        </div>
    </div>

    <!-- Client Confirmation -->
    <?php if ($client_confirm): ?>
    <div class="card">
        <div class="card-title"><i class="ti ti-user-check" style="color:var(--success)"></i> Client Approval</div>
        <div style="font-size:.85rem">
            <div style="display:flex;align-items:center;gap:.5rem;margin-bottom:.5rem">
                <span class="badge <?= $client_confirm['confirmation_status']==='Confirmed' ? 'badge-paid' : 'badge-overdue' ?>">
                    <?= htmlspecialchars($client_confirm['confirmation_status']) ?>
                </span>
            </div>
            <?php if ($client_confirm['confirmed_at']): ?>
            <div style="color:var(--text2);font-size:.78rem">
                <i class="ti ti-calendar" style="font-size:.8rem"></i>
                <?= date('d M Y, H:i', strtotime($client_confirm['confirmed_at'])) ?>
            </div>
            <?php endif; ?>
            <?php if ($client_confirm['confirmation_notes']): ?>
            <div style="margin-top:.5rem;padding:.65rem;background:var(--surface2);border-radius:8px;font-size:.78rem;color:var(--text2)">
                <?= htmlspecialchars($client_confirm['confirmation_notes']) ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
    <?php endif; ?>

    <!-- Payments -->
    <div class="card">
        <div class="card-title"><i class="ti ti-credit-card" style="color:var(--accent)"></i> Payments
            <?php if (!empty($payments)): ?>
            <span class="badge badge-submitted" style="margin-left:auto"><?= count($payments) ?></span>
            <?php endif; ?>
        </div>
        <?php if (empty($payments)): ?>
            <div class="empty-state" style="padding:1.5rem"><i class="ti ti-inbox"></i><p>No payments recorded yet.</p></div>
        <?php else: ?>
        <?php foreach ($payments as $pay):
            $picon  = match($pay['STATUS']) { 'Verified'=>'circle-check', 'Pending'=>'hourglass', 'Rejected'=>'x-circle', default=>'credit-card' };
            $pclass = match($pay['STATUS']) { 'Verified'=>'verified', 'Pending'=>'pending', default=>'rejected' };
        ?>
        <div class="payment-card">
            <div class="pay-icon <?= $pclass ?>">
                <i class="ti ti-<?= $picon ?>"></i>
            </div>
            <div style="flex:1;min-width:0">
                <div style="font-weight:600;font-size:.85rem;color:var(--text)">
                    E <?= number_format((float)$pay['AMOUNT_PAID'], 2) ?>
                    <span class="badge badge-<?= $pclass==='verified'?'paid':($pclass==='pending'?'pending':'overdue') ?>" style="margin-left:.4rem;font-size:.68rem">
                        <?= htmlspecialchars($pay['STATUS']) ?>
                    </span>
                </div>
                <div style="font-size:.78rem;color:var(--text2);margin-top:.2rem">
                    <?= htmlspecialchars($pay['METHOD'] ?? 'N/A') ?>
                    <?php if ($pay['REFERENCE_NUMBER']): ?>
                    · Ref: <code style="font-size:.75rem"><?= htmlspecialchars($pay['REFERENCE_NUMBER']) ?></code>
                    <?php endif; ?>
                </div>
                <div style="font-size:.72rem;color:var(--text2);margin-top:.15rem">
                    <?= $pay['PAYMENT_DATE'] ? date('d M Y', strtotime($pay['PAYMENT_DATE'])) : '—' ?>
                </div>
            </div>
            <?php if ($pay['RECEIPT_ID']): ?>
            <a href="payment_verification.php?payment_id=<?= $pay['PAYMENT_ID'] ?>" class="btn btn-sm btn-secondary" title="View Receipt">
                <i class="ti ti-receipt"></i>
            </a>
            <?php endif; ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($is_invoice && $status === 'Pending Payment'): ?>
        <a href="payment_verification.php" class="btn btn-success btn-sm" style="margin-top:.75rem;width:100%;justify-content:center">
            <i class="ti ti-circle-check"></i> Verify Payments
        </a>
        <?php endif; ?>
    </div>

    <!-- Audit Trail -->
    <div class="card">
        <div class="card-title"><i class="ti ti-history" style="color:var(--accent)"></i> Audit Trail</div>
        <?php if (empty($tracking)): ?>
            <div class="empty-state" style="padding:1rem"><i class="ti ti-inbox"></i><p>No activity yet.</p></div>
        <?php else: ?>
        <div style="position:relative">
        <?php foreach ($tracking as $i => $t):
            $ticon = match(true) {
                str_contains($t['action'], 'Generated') => 'file-check',
                str_contains($t['action'], 'Sent')      => 'send',
                str_contains($t['action'], 'Paid')      => 'circle-check',
                str_contains($t['action'], 'Submitted') => 'upload',
                default                                  => 'clock',
            };
            $tcolor = match(true) {
                str_contains($t['action'], 'Generated') => 'var(--accent)',
                str_contains($t['action'], 'Sent')      => 'var(--info)',
                str_contains($t['action'], 'Paid')      => 'var(--success)',
                default                                  => 'var(--text2)',
            };
        ?>
        <div class="timeline-item">
            <?php if ($i < count($tracking) - 1): ?><div class="tl-line"></div><?php endif; ?>
            <div class="tl-dot" style="border-color:<?= $tcolor ?>;color:<?= $tcolor ?>">
                <i class="ti ti-<?= $ticon ?>"></i>
            </div>
            <div class="tl-body">
                <div class="tl-action"><?= htmlspecialchars($t['action']) ?></div>
                <?php if ($t['description']): ?>
                <div class="tl-desc"><?= htmlspecialchars(mb_strimwidth($t['description'], 0, 100, '…')) ?></div>
                <?php endif; ?>
                <div class="tl-time">
                    <?= $t['FULL_NAME'] ? htmlspecialchars($t['FULL_NAME']) . ' · ' : '' ?>
                    <?= date('d M Y, H:i', strtotime($t['created_at'])) ?>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>

</div><!-- /.right -->
</div><!-- /.grid -->

<!-- ══ GENERATE INVOICE MODAL ══════════════════════════════════════════════════ -->
<?php if ($can_generate): ?>
<div id="generateModal" style="display:none;position:fixed;inset:0;background:rgba(0,0,0,.7);backdrop-filter:blur(4px);z-index:1000;align-items:center;justify-content:center;padding:1rem">
    <div style="background:var(--surface);border:1px solid var(--accent);border-radius:14px;width:100%;max-width:520px;box-shadow:0 20px 60px rgba(0,0,0,.6);animation:fadeIn .25s ease">
        <div style="padding:1.25rem 1.5rem;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;align-items:center">
            <div>
                <div style="font-size:1rem;font-weight:700;color:var(--text)"><i class="ti ti-file-check" style="color:var(--accent)"></i> Generate Invoice</div>
                <div style="font-size:.78rem;color:var(--text2);margin-top:.2rem">Convert <?= $inv_num ?> to a formal invoice</div>
            </div>
            <button onclick="document.getElementById('generateModal').style.display='none'" style="background:none;border:none;color:var(--text2);cursor:pointer;font-size:1.25rem"><i class="ti ti-x"></i></button>
        </div>
        <form method="POST">
            <input type="hidden" name="action" value="generate_invoice">
            <div style="padding:1.5rem">

                <!-- Summary -->
                <div style="background:rgba(240,165,0,.07);border:1px solid rgba(240,165,0,.2);border-radius:8px;padding:1rem;margin-bottom:1.25rem">
                    <div style="display:flex;justify-content:space-between;margin-bottom:.4rem;font-size:.85rem">
                        <span style="color:var(--text2)">Quotation</span><strong><?= $inv_num ?></strong>
                    </div>
                    <div style="display:flex;justify-content:space-between;margin-bottom:.4rem;font-size:.85rem">
                        <span style="color:var(--text2)">Client</span><strong><?= htmlspecialchars($inv['COMPANY_NAME'] ?? '—') ?></strong>
                    </div>
                    <div style="display:flex;justify-content:space-between;margin-bottom:.4rem;font-size:.85rem">
                        <span style="color:var(--text2)">Fault Ref</span><strong><?= htmlspecialchars($fault_ref) ?></strong>
                    </div>
                    <div style="display:flex;justify-content:space-between;font-size:.85rem;padding-top:.5rem;border-top:1px solid rgba(240,165,0,.2)">
                        <span style="color:var(--text2)">Total Amount</span>
                        <strong style="color:var(--accent);font-size:1.1rem">E <?= number_format((float)$inv['TOTAL'], 2) ?></strong>
                    </div>
                </div>

                <!-- Line items summary -->
                <?php if (!empty($lines)): ?>
                <div style="margin-bottom:1.25rem">
                    <div style="font-size:.75rem;font-weight:700;text-transform:uppercase;letter-spacing:.07em;color:var(--text2);margin-bottom:.5rem">Quotation Line Items</div>
                    <?php foreach ($lines as $line): ?>
                    <div style="display:flex;justify-content:space-between;font-size:.8rem;padding:.3rem 0;border-bottom:1px solid var(--border)">
                        <span style="color:var(--text2)"><?= htmlspecialchars($line['DESCRIPTION'] ?? '') ?></span>
                        <span style="color:var(--text);font-weight:600">E <?= number_format((float)$line['LINE_TOTAL'], 2) ?></span>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php endif; ?>

                <div class="form-group">
                    <label>Payment Due Date <span style="color:var(--danger)">*</span></label>
                    <input type="date" name="due_date" class="form-control" required
                           min="<?= date('Y-m-d', strtotime('+1 day')) ?>"
                           value="<?= date('Y-m-d', strtotime('+14 days')) ?>">
                </div>
                <div class="form-group">
                    <label>Internal Notes (optional)</label>
                    <textarea name="notes" class="form-control" placeholder="Any notes for your records…" style="min-height:70px"></textarea>
                </div>
            </div>
            <div style="padding:1rem 1.5rem;border-top:1px solid var(--border);display:flex;gap:.75rem;justify-content:flex-end">
                <button type="button" onclick="document.getElementById('generateModal').style.display='none'" class="btn btn-secondary">
                    Cancel
                </button>
                <button type="submit" class="btn btn-primary">
                    <i class="ti ti-file-check"></i> Generate &amp; Notify Client
                </button>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>

<?php require_once '../../includes/acc_footer.php'; ?>

