<?php
$page_title    = 'Generate Invoice';
$page_subtitle = 'Client-Approved Faults Ready for Invoicing';
require_once __DIR__ . '/../../includes/acc_header.php';

$success_msg = '';
$error_msg   = '';

// ── Handle: Generate Invoice ──────────────────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'generate') {
    $invoice_id = (int)($_POST['invoice_id'] ?? 0);
    $due_date   = mysqli_real_escape_string($conn, $_POST['due_date'] ?? '');
    $notes      = mysqli_real_escape_string($conn, $_POST['notes'] ?? '');

    $chk = mysqli_query($conn, "
        SELECT i.*, c.COMPANY_NAME, c.COMPANY_EMAIL, c.CLIENT_ID,
               rf.REP_FAULT_ID, rf.STATUS as FAULT_STATUS
        FROM invoice i
        LEFT JOIN client c ON i.CLIENT_ID = c.CLIENT_ID
        LEFT JOIN assignment a ON i.ASSIGN_ID = a.ASSIGN_ID
        LEFT JOIN reported_fault rf ON a.REP_FAULT_ID = rf.REP_FAULT_ID
        WHERE i.INVOICE_ID = $invoice_id AND i.TYPE = 'Quotation'");

    if (mysqli_num_rows($chk) === 0) {
        $error_msg = 'Invalid quotation selected.';
    } elseif (empty($due_date)) {
        $error_msg = 'Please set a payment due date.';
    } else {
        $quot  = mysqli_fetch_assoc($chk);
        $today = date('Y-m-d');

        $upd = mysqli_query($conn, "
            UPDATE invoice SET
                TYPE         = 'Invoice',
                STATUS       = 'Pending Payment',
                INVOICE_DATE = '$today',
                DUE_DATE     = '$due_date'
            WHERE INVOICE_ID = $invoice_id
        ");

        if ($upd) {
            $inv_ref   = 'INV-' . str_pad($invoice_id, 4, '0', STR_PAD_LEFT);
            $total_fmt = number_format($quot['TOTAL'], 2);
            $client_id = (int)$quot['CLIENT_ID'];

            // Audit trail
            mysqli_query($conn, "
                INSERT INTO invoice_tracking (invoice_id, action, description, performed_by_id, performed_by_role)
                VALUES ($invoice_id, 'Invoice Generated',
                    'Invoice $inv_ref generated by accountant. Due: $due_date. Notes: $notes',
                    $acc_id, 'Accountant')
            ");

            // Notify client
            mysqli_query($conn, "
                INSERT INTO notifications (user_id, user_type, title, message)
                VALUES ($client_id, 'Client',
                    'Invoice $inv_ref Ready for Payment',
                    'Your invoice $inv_ref for E$total_fmt has been generated. Payment is due by $due_date. Please log in to make payment.')
            ");

            // Notify admin
            mysqli_query($conn, "
                INSERT INTO notifications (user_id, user_type, title, message)
                VALUES (1, 'Admin',
                    'Invoice $inv_ref Generated',
                    'Accountant generated invoice $inv_ref (E$total_fmt) for client. Due: $due_date.')
            ");

            $success_msg = "Invoice $inv_ref generated and sent to client successfully!";
        } else {
            $error_msg = 'Database error: ' . mysqli_error($conn);
        }
    }
}

// ── Handle: Re-send Invoice Notification ──────────────────────────────────────
if ($_SERVER['REQUEST_METHOD'] === 'POST' && ($_POST['action'] ?? '') === 'resend') {
    $invoice_id = (int)($_POST['invoice_id'] ?? 0);

    $inv = mysqli_query($conn, "
        SELECT i.*, c.COMPANY_NAME, c.CLIENT_ID
        FROM invoice i
        LEFT JOIN client c ON i.CLIENT_ID = c.CLIENT_ID
        WHERE i.INVOICE_ID = $invoice_id AND i.TYPE = 'Invoice'");

    if (mysqli_num_rows($inv) > 0) {
        $row       = mysqli_fetch_assoc($inv);
        $client_id = (int)$row['CLIENT_ID'];
        $inv_ref   = 'INV-' . str_pad($invoice_id, 4, '0', STR_PAD_LEFT);
        $total_fmt = number_format($row['TOTAL'], 2);
        $due       = $row['DUE_DATE'];

        mysqli_query($conn, "
            INSERT INTO notifications (user_id, user_type, title, message)
            VALUES ($client_id, 'Client',
                'Reminder: Invoice $inv_ref Awaiting Payment',
                'This is a reminder that invoice $inv_ref for E$total_fmt is due on $due. Please log in to complete payment.')
        ");

        mysqli_query($conn, "
            INSERT INTO invoice_tracking (invoice_id, action, description, performed_by_id, performed_by_role)
            VALUES ($invoice_id, 'Payment Reminder Sent',
                'Payment reminder sent to client by accountant.',
                $acc_id, 'Accountant')
        ");

        $success_msg = "Payment reminder for $inv_ref sent to client.";
    } else {
        $error_msg = 'Invoice not found.';
    }
}

// ── Load: Client-Approved faults ready for invoicing ─────────────────────────
// These are quotations linked to faults with STATUS = 'Client Approved'
$approved_ready = mysqli_query($conn, "
    SELECT
        i.INVOICE_ID, i.TOTAL, i.INVOICE_DATE, i.STATUS as QUOT_STATUS,
        c.COMPANY_NAME, c.COMPANY_EMAIL, c.CLIENT_ID, c.CONTACT_PERSON_NAME,
        rf.REP_FAULT_ID, rf.STATUS as FAULT_STATUS, rf.PRIORITY, rf.REPORT_DATE,
        rf.DESCRIPTION as FAULT_DESC,
        a.ASSIGN_ID, a.ASSIGN_DATE,
        e.FULL_NAME as TECH_NAME,
        cc.confirmed_at as CLIENT_APPROVED_AT,
        cc.confirmation_notes
    FROM invoice i
    INNER JOIN assignment a       ON i.ASSIGN_ID    = a.ASSIGN_ID
    INNER JOIN reported_fault rf  ON a.REP_FAULT_ID = rf.REP_FAULT_ID
    LEFT JOIN  client c           ON i.CLIENT_ID    = c.CLIENT_ID
    LEFT JOIN  assignment_technician at2 ON a.ASSIGN_ID = at2.ASSIGN_ID
    LEFT JOIN  employee e         ON at2.EMP_ID     = e.EMP_ID
    LEFT JOIN  client_confirmations cc ON cc.fault_id = rf.REP_FAULT_ID
    WHERE i.TYPE   = 'Quotation'
      AND rf.STATUS = 'Client Approved'
    GROUP BY i.INVOICE_ID
    ORDER BY cc.confirmed_at DESC, i.INVOICE_DATE DESC
");

// ── Load: Recently Generated Invoices ─────────────────────────────────────────
$recent_invoices = mysqli_query($conn, "
    SELECT i.INVOICE_ID, i.TOTAL, i.PAID_AMOUNT, i.STATUS,
           i.INVOICE_DATE, i.DUE_DATE,
           c.COMPANY_NAME, c.CLIENT_ID,
           rf.REP_FAULT_ID
    FROM invoice i
    LEFT JOIN client c          ON i.CLIENT_ID  = c.CLIENT_ID
    LEFT JOIN assignment a      ON i.ASSIGN_ID  = a.ASSIGN_ID
    LEFT JOIN reported_fault rf ON a.REP_FAULT_ID = rf.REP_FAULT_ID
    WHERE i.TYPE = 'Invoice'
    ORDER BY i.INVOICE_DATE DESC
    LIMIT 10
");

// ── Stats ──────────────────────────────────────────────────────────────────────
$r = mysqli_query($conn, "SELECT COUNT(*) c FROM invoice i INNER JOIN assignment a ON i.ASSIGN_ID = a.ASSIGN_ID INNER JOIN reported_fault rf ON a.REP_FAULT_ID = rf.REP_FAULT_ID WHERE i.TYPE='Quotation' AND rf.STATUS='Client Approved'");
$ready_count = mysqli_fetch_assoc($r)['c'] ?? 0;

$r = mysqli_query($conn, "SELECT COUNT(*) c FROM invoice WHERE TYPE='Invoice' AND MONTH(INVOICE_DATE)=MONTH(NOW()) AND YEAR(INVOICE_DATE)=YEAR(NOW())");
$inv_month = mysqli_fetch_assoc($r)['c'] ?? 0;

$r = mysqli_query($conn, "SELECT COALESCE(SUM(TOTAL),0) t FROM invoice WHERE TYPE='Invoice' AND MONTH(INVOICE_DATE)=MONTH(NOW()) AND YEAR(INVOICE_DATE)=YEAR(NOW())");
$rev_month = mysqli_fetch_assoc($r)['t'] ?? 0;

$r = mysqli_query($conn, "SELECT COUNT(*) c FROM invoice WHERE TYPE='Invoice' AND STATUS='Pending Payment'");
$awaiting_pay = mysqli_fetch_assoc($r)['c'] ?? 0;
?>

<style>
/* ── Workflow Steps ── */
.wf-bar {
    display: flex;
    gap: 0;
    margin-bottom: 2rem;
    border-radius: 10px;
    overflow: hidden;
    border: 1px solid var(--border);
}
.wf-step {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    gap: .25rem;
    padding: .75rem .5rem;
    font-size: .72rem;
    font-weight: 600;
    color: var(--text2);
    background: var(--surface2);
    border-right: 1px solid var(--border);
    position: relative;
    text-align: center;
}
.wf-step:last-child { border-right: none; }
.wf-step .wf-icon { font-size: 1.1rem; margin-bottom: .1rem; }
.wf-step.done  { background: rgba(63,185,80,.08); color: var(--success); }
.wf-step.done .wf-icon { color: var(--success); }
.wf-step.active { background: rgba(240,165,0,.1); color: var(--accent); }
.wf-step.active .wf-icon { color: var(--accent); }
.wf-step.pending { opacity: .5; }

/* ── Approved fault cards ── */
.approved-card {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 12px;
    overflow: hidden;
    transition: border-color .2s, transform .15s;
}
.approved-card:hover { border-color: var(--accent); transform: translateY(-2px); }
.approved-card.selected { border-color: var(--accent); box-shadow: 0 0 0 2px rgba(240,165,0,.2); }

.ac-top {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    padding: 1rem 1.25rem;
    gap: 1rem;
    cursor: pointer;
    flex-wrap: wrap;
}
.ac-left { flex: 1; min-width: 0; }
.ac-company { font-size: 1rem; font-weight: 700; color: var(--text); margin-bottom: .2rem; }
.ac-fault-ref { font-size: .78rem; color: var(--text2); margin-bottom: .5rem; }
.ac-meta { display: flex; flex-wrap: wrap; gap: .4rem; }
.ac-pill {
    display: inline-flex; align-items: center; gap: .3rem;
    padding: .2rem .6rem; border-radius: 6px; font-size: .72rem; font-weight: 600;
    background: var(--surface2); border: 1px solid var(--border); color: var(--text2);
}
.ac-pill.green { background: rgba(63,185,80,.1); border-color: rgba(63,185,80,.25); color: var(--success); }
.ac-pill.blue  { background: rgba(88,166,255,.1); border-color: rgba(88,166,255,.25); color: var(--info); }
.ac-pill.orange { background: rgba(240,165,0,.1); border-color: rgba(240,165,0,.25); color: var(--accent); }
.ac-pill.red   { background: rgba(248,81,73,.1); border-color: rgba(248,81,73,.25); color: var(--danger); }

.ac-right { text-align: right; flex-shrink: 0; }
.ac-total { font-size: 1.6rem; font-weight: 800; color: var(--accent); line-height: 1; }
.ac-total-label { font-size: .68rem; color: var(--text2); margin-top: .2rem; text-transform: uppercase; letter-spacing: .06em; }

.ac-approved-banner {
    background: rgba(63,185,80,.08);
    border-top: 1px solid rgba(63,185,80,.2);
    padding: .6rem 1.25rem;
    display: flex;
    align-items: center;
    gap: .5rem;
    font-size: .78rem;
    color: var(--success);
}

.ac-body {
    padding: 0 1.25rem 1.25rem;
    display: none;
}
.ac-body.open { display: block; }

/* Line items mini table */
.line-mini { width: 100%; border-collapse: collapse; margin: .75rem 0; }
.line-mini th { font-size: .7rem; color: var(--text2); font-weight: 600; text-transform: uppercase; padding: .4rem .6rem; background: var(--surface2); border: 1px solid var(--border); }
.line-mini td { font-size: .8rem; padding: .4rem .6rem; border: 1px solid var(--border); color: var(--text); }
.line-mini tr:nth-child(even) td { background: rgba(255,255,255,.02); }
.line-mini td:last-child { font-weight: 600; color: var(--accent); text-align: right; }
.line-mini td:nth-child(2), .line-mini td:nth-child(3) { text-align: center; }
.line-mini .total-row td { background: rgba(240,165,0,.07); font-weight: 700; color: var(--accent); font-size: .85rem; }

/* Invoice modal overlay */
.modal-overlay {
    position: fixed; inset: 0; background: rgba(0,0,0,.7);
    z-index: 9000; display: flex; align-items: center; justify-content: center;
    padding: 1.5rem; display: none;
}
.modal-overlay.open { display: flex; }
.modal-box {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 16px; width: 100%; max-width: 720px; max-height: 90vh;
    overflow-y: auto; animation: fadeIn .25s ease;
}
.modal-head {
    display: flex; align-items: center; justify-content: space-between;
    padding: 1.25rem 1.5rem; border-bottom: 1px solid var(--border);
    position: sticky; top: 0; background: var(--surface); z-index: 1;
}
.modal-head h2 { font-size: 1.1rem; font-weight: 700; }
.modal-body { padding: 1.5rem; }

/* Invoice preview inside modal */
.inv-preview-wrap {
    background: var(--surface2); border: 1px solid var(--border);
    border-radius: 10px; padding: 1.5rem; margin-bottom: 1.25rem;
}
.inv-brand { font-size: 1.3rem; font-weight: 800; color: var(--accent); margin-bottom: .1rem; }
.inv-brand span { color: var(--text); }
.inv-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin: 1rem 0; }
.inv-party { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: .75rem 1rem; }
.inv-party .lbl { font-size: .68rem; text-transform: uppercase; letter-spacing: .07em; color: var(--text2); font-weight: 700; margin-bottom: .3rem; }
.inv-party .nm  { font-size: .9rem; font-weight: 600; color: var(--text); }
.inv-party .sub { font-size: .78rem; color: var(--text2); margin-top: .15rem; }

/* Recently generated invoices table */
.inv-row { display: flex; align-items: center; gap: .75rem; padding: .75rem; background: var(--surface2); border-radius: 8px; border: 1px solid var(--border); margin-bottom: .4rem; text-decoration: none; transition: background .2s; }
.inv-row:hover { background: rgba(255,255,255,.04); }
.inv-row .ir-num { font-size: .85rem; font-weight: 700; color: var(--text); min-width: 90px; }
.inv-row .ir-company { font-size: .8rem; color: var(--text2); flex: 1; }
.inv-row .ir-right { text-align: right; flex-shrink: 0; }
.inv-row .ir-amount { font-size: .88rem; font-weight: 700; color: var(--accent); }
.send-btn { background: rgba(88,166,255,.12); color: var(--info); border: 1px solid rgba(88,166,255,.3); border-radius: 6px; padding: .3rem .65rem; font-size: .75rem; font-weight: 600; cursor: pointer; display: inline-flex; align-items: center; gap: .3rem; transition: background .2s; }
.send-btn:hover { background: rgba(88,166,255,.22); }

/* Priority badge colours */
.pri-High   { background:rgba(248,81,73,.12); color:var(--danger);  border-color:rgba(248,81,73,.3); }
.pri-Medium { background:rgba(240,165,0,.12); color:var(--accent);  border-color:rgba(240,165,0,.3); }
.pri-Low    { background:rgba(88,166,255,.1); color:var(--info);    border-color:rgba(88,166,255,.3); }
</style>

<?php if ($success_msg): ?>
<div class="alert alert-success"><i class="ti ti-circle-check"></i> <?= htmlspecialchars($success_msg) ?></div>
<?php endif; ?>
<?php if ($error_msg): ?>
<div class="alert alert-danger"><i class="ti ti-alert-circle"></i> <?= htmlspecialchars($error_msg) ?></div>
<?php endif; ?>

<!-- Page Header -->
<div class="page-head">
    <div>
        <h1><i class="ti ti-file-text" style="color:var(--accent)"></i> Generate Invoice</h1>
        <p>Faults approved by clients are listed below — review, generate, and send invoices for payment</p>
    </div>
    <div style="display:flex;gap:.5rem">
        <a href="acc_invoices.php" class="btn btn-secondary btn-sm"><i class="ti ti-receipt"></i> All Invoices</a>
        <a href="accountant_dashboard.php" class="btn btn-secondary btn-sm"><i class="ti ti-layout-dashboard"></i> Dashboard</a>
    </div>
</div>

<!-- Workflow Progress Bar -->
<div class="wf-bar" style="margin-bottom:2rem">
    <div class="wf-step done">
        <span class="wf-icon"><i class="ti ti-user-circle"></i></span>
        <span>1. Client Reports</span>
    </div>
    <div class="wf-step done">
        <span class="wf-icon"><i class="ti ti-clipboard-check"></i></span>
        <span>2. Admin Assigns</span>
    </div>
    <div class="wf-step done">
        <span class="wf-icon"><i class="ti ti-tool"></i></span>
        <span>3. Tech Works</span>
    </div>
    <div class="wf-step done">
        <span class="wf-icon"><i class="ti ti-file-invoice"></i></span>
        <span>4. Tech Quotes</span>
    </div>
    <div class="wf-step done">
        <span class="wf-icon"><i class="ti ti-thumb-up"></i></span>
        <span>5. Client Approves</span>
    </div>
    <div class="wf-step active">
        <span class="wf-icon"><i class="ti ti-file-text"></i></span>
        <span>6. Generate Invoice ◀ You Are Here</span>
    </div>
    <div class="wf-step pending">
        <span class="wf-icon"><i class="ti ti-credit-card"></i></span>
        <span>7. Client Pays</span>
    </div>
    <div class="wf-step pending">
        <span class="wf-icon"><i class="ti ti-circle-check"></i></span>
        <span>8. Verify & Close</span>
    </div>
</div>

<!-- Stats -->
<div class="grid-4" style="margin-bottom:1.5rem">
    <div class="stat-card">
        <div class="stat-icon green"><i class="ti ti-thumb-up"></i></div>
        <div>
            <div class="stat-num"><?= $ready_count ?></div>
            <div class="stat-label">Ready to Invoice</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon blue"><i class="ti ti-receipt"></i></div>
        <div>
            <div class="stat-num"><?= $inv_month ?></div>
            <div class="stat-label">Invoiced This Month</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon orange"><i class="ti ti-currency"></i></div>
        <div>
            <div class="stat-num">E<?= number_format($rev_month, 2) ?></div>
            <div class="stat-label">Revenue This Month</div>
        </div>
    </div>
    <div class="stat-card">
        <div class="stat-icon purple"><i class="ti ti-clock"></i></div>
        <div>
            <div class="stat-num"><?= $awaiting_pay ?></div>
            <div class="stat-label">Awaiting Payment</div>
        </div>
    </div>
</div>

<!-- Main 2-column grid -->
<div style="display:grid;grid-template-columns:1fr 380px;gap:1.5rem;align-items:flex-start">

<!-- LEFT: Approved Faults Ready for Invoicing -->
<div>
    <div class="card">
        <div class="card-title" style="justify-content:space-between">
            <span><i class="ti ti-thumb-up" style="color:var(--success)"></i> Client-Approved — Ready to Invoice</span>
            <?php if ($ready_count > 0): ?>
            <span style="font-size:.75rem;background:rgba(63,185,80,.1);border:1px solid rgba(63,185,80,.25);color:var(--success);padding:.2rem .6rem;border-radius:99px;font-weight:700"><?= $ready_count ?> pending</span>
            <?php endif; ?>
        </div>

        <?php if (mysqli_num_rows($approved_ready) === 0): ?>
        <div class="empty-state">
            <i class="ti ti-mood-happy"></i>
            <p style="font-size:.95rem;font-weight:600;color:var(--text)">All clear! No approved faults awaiting invoicing.</p>
            <p style="font-size:.82rem;margin-top:.4rem">Once a client approves completed work, those jobs appear here for you to generate an invoice.</p>
        </div>
        <?php else: ?>

        <div style="font-size:.8rem;color:var(--text2);margin-bottom:1rem;padding:.65rem 1rem;background:rgba(63,185,80,.06);border:1px solid rgba(63,185,80,.18);border-radius:8px;display:flex;align-items:center;gap:.5rem">
            <i class="ti ti-info-circle" style="color:var(--success)"></i>
            Click a card to expand details, then click <strong style="color:var(--text)">Generate Invoice</strong> to create and send the invoice to the client.
        </div>

        <div style="display:flex;flex-direction:column;gap:.75rem" id="approved-list">
        <?php while ($q = mysqli_fetch_assoc($approved_ready)):
            $inv_num    = 'QUO-' . str_pad($q['INVOICE_ID'], 4, '0', STR_PAD_LEFT);
            $fault_line = explode("\n", $q['FAULT_DESC'] ?? '')[0];
            $fault_title = '';
            if (preg_match('/FAULT TITLE:\s*(.+)/i', $q['FAULT_DESC'] ?? '', $m)) $fault_title = trim($m[1]);
            $fault_cat   = '';
            if (preg_match('/CATEGORY:\s*(.+)/i', $q['FAULT_DESC'] ?? '', $m)) $fault_cat = trim($m[1]);
            $approved_time = $q['CLIENT_APPROVED_AT'] ? date('d M Y H:i', strtotime($q['CLIENT_APPROVED_AT'])) : 'Recently';
            $priority_cls  = 'pri-' . ($q['PRIORITY'] ?? 'Low');
        ?>
        <div class="approved-card" id="ac-<?= $q['INVOICE_ID'] ?>">

            <!-- Top clickable section -->
            <div class="ac-top" onclick="toggleCard(<?= $q['INVOICE_ID'] ?>)">
                <div class="ac-left">
                    <div class="ac-company">
                        <i class="ti ti-building" style="color:var(--accent);font-size:.9rem"></i>
                        <?= htmlspecialchars($q['COMPANY_NAME'] ?? 'Unknown Client') ?>
                    </div>
                    <div class="ac-fault-ref">
                        Fault #<?= $q['REP_FAULT_ID'] ?> &nbsp;·&nbsp;
                        <?= $inv_num ?> &nbsp;·&nbsp;
                        Technician: <?= htmlspecialchars($q['TECH_NAME'] ?? 'N/A') ?>
                    </div>
                    <?php if ($fault_title): ?>
                    <div style="font-size:.82rem;color:var(--text);font-weight:600;margin-bottom:.5rem"><?= htmlspecialchars($fault_title) ?></div>
                    <?php endif; ?>
                    <div class="ac-meta">
                        <span class="ac-pill green"><i class="ti ti-check"></i> Client Approved</span>
                        <span class="ac-pill <?= $priority_cls ?>"><i class="ti ti-flag"></i> <?= $q['PRIORITY'] ?? 'Low' ?> Priority</span>
                        <?php if ($fault_cat): ?>
                        <span class="ac-pill blue"><i class="ti ti-tag"></i> <?= htmlspecialchars($fault_cat) ?></span>
                        <?php endif; ?>
                        <span class="ac-pill"><i class="ti ti-calendar"></i> Reported: <?= date('d M Y', strtotime($q['REPORT_DATE'])) ?></span>
                    </div>
                </div>
                <div class="ac-right">
                    <div class="ac-total">E<?= number_format($q['TOTAL'], 2) ?></div>
                    <div class="ac-total-label">Quotation Total</div>
                    <div style="margin-top:.5rem">
                        <span style="font-size:.72rem;color:var(--text2)"><i class="ti ti-chevron-down" id="chev-<?= $q['INVOICE_ID'] ?>"></i> Expand</span>
                    </div>
                </div>
            </div>

            <!-- Client approved banner -->
            <div class="ac-approved-banner">
                <i class="ti ti-shield-check"></i>
                Client confirmed work completion on <strong><?= $approved_time ?></strong>
                <?php if (!empty($q['confirmation_notes'])): ?>
                 &nbsp;·&nbsp; <em>"<?= htmlspecialchars(mb_strimwidth($q['confirmation_notes'], 0, 60, '...')) ?>"</em>
                <?php endif; ?>
            </div>

            <!-- Expandable body -->
            <div class="ac-body" id="acb-<?= $q['INVOICE_ID'] ?>">
                <hr style="border:none;border-top:1px solid var(--border);margin:.75rem 0">

                <!-- Line items fetched via PHP -->
                <?php
                $lines = mysqli_query($conn, "SELECT * FROM invoice_line WHERE INVOICE_ID = {$q['INVOICE_ID']} ORDER BY LINE_ID");
                $line_rows = [];
                while ($l = mysqli_fetch_assoc($lines)) $line_rows[] = $l;
                ?>
                <?php if (!empty($line_rows)): ?>
                <div style="font-size:.8rem;font-weight:700;color:var(--text2);text-transform:uppercase;letter-spacing:.05em;margin-bottom:.4rem">Quotation Line Items</div>
                <table class="line-mini">
                    <thead>
                        <tr>
                            <th>Description</th>
                            <th style="text-align:center">Qty</th>
                            <th style="text-align:center">Unit Price</th>
                            <th style="text-align:right">Line Total</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($line_rows as $l): ?>
                        <tr>
                            <td><?= htmlspecialchars($l['DESCRIPTION']) ?></td>
                            <td style="text-align:center"><?= $l['QUANTITY'] ?></td>
                            <td style="text-align:center">E<?= number_format($l['UNIT_PRICE'], 2) ?></td>
                            <td>E<?= number_format($l['LINE_TOTAL'], 2) ?></td>
                        </tr>
                    <?php endforeach; ?>
                        <tr class="total-row">
                            <td colspan="3" style="text-align:right;font-size:.82rem">QUOTATION TOTAL</td>
                            <td>E<?= number_format($q['TOTAL'], 2) ?></td>
                        </tr>
                    </tbody>
                </table>
                <?php else: ?>
                <div style="font-size:.8rem;color:var(--text2);padding:.5rem 0">No line items found for this quotation.</div>
                <?php endif; ?>

                <!-- Generate Invoice Form -->
                <div style="background:rgba(240,165,0,.05);border:1px solid rgba(240,165,0,.2);border-radius:10px;padding:1.1rem;margin-top:1rem">
                    <div style="font-size:.85rem;font-weight:700;color:var(--accent);margin-bottom:.85rem;display:flex;align-items:center;gap:.4rem">
                        <i class="ti ti-file-text"></i> Generate & Send Invoice to Client
                    </div>
                    <form method="POST">
                        <input type="hidden" name="action" value="generate">
                        <input type="hidden" name="invoice_id" value="<?= $q['INVOICE_ID'] ?>">

                        <div style="display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-bottom:.75rem">
                            <div class="form-group" style="margin:0">
                                <label>Invoice Date</label>
                                <input type="text" class="form-control" value="<?= date('d M Y') ?>" readonly style="opacity:.65">
                            </div>
                            <div class="form-group" style="margin:0">
                                <label>Payment Due Date <span style="color:var(--danger)">*</span></label>
                                <input type="date" name="due_date" class="form-control"
                                       min="<?= date('Y-m-d', strtotime('+1 day')) ?>"
                                       value="<?= date('Y-m-d', strtotime('+14 days')) ?>" required>
                            </div>
                        </div>
                        <div class="form-group" style="margin-bottom:.75rem">
                            <label>Notes for Client (optional)</label>
                            <textarea name="notes" class="form-control" style="min-height:60px" placeholder="e.g. Payment via bank transfer preferred. Contact finance@busiquip.com for queries."></textarea>
                        </div>

                        <div style="display:flex;gap:.6rem;flex-wrap:wrap;align-items:center">
                            <button type="submit" class="btn btn-primary">
                                <i class="ti ti-file-check"></i> Generate Invoice & Notify Client
                            </button>
                            <button type="button" class="btn btn-info btn-sm"
                                onclick="openPreview(<?= $q['INVOICE_ID'] ?>, '<?= addslashes($q['COMPANY_NAME'] ?? 'Unknown') ?>', <?= $q['TOTAL'] ?>, '<?= addslashes($q['CONTACT_PERSON_NAME'] ?? '') ?>', <?= $q['REP_FAULT_ID'] ?>)">
                                <i class="ti ti-eye"></i> Preview Invoice
                            </button>
                            <span style="font-size:.75rem;color:var(--text2)">
                                <i class="ti ti-send"></i> Client will receive a notification instantly
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php endwhile; ?>
        </div>
        <?php endif; ?>
    </div>
</div>

<!-- RIGHT: Recently Generated + Awaiting Payment -->
<div style="display:flex;flex-direction:column;gap:1.25rem">

    <!-- Recently Generated Invoices -->
    <div class="card">
        <div class="card-title"><i class="ti ti-history" style="color:var(--accent)"></i> Generated Invoices</div>

        <?php if (mysqli_num_rows($recent_invoices) === 0): ?>
        <div class="empty-state" style="padding:1.5rem"><i class="ti ti-inbox"></i><p>No invoices generated yet</p></div>
        <?php else: ?>

        <div style="display:flex;flex-direction:column;gap:.4rem">
        <?php
        mysqli_data_seek($recent_invoices, 0);
        while ($inv = mysqli_fetch_assoc($recent_invoices)):
            $today_dt = date('Y-m-d');
            $is_overdue = ($inv['STATUS'] !== 'Paid' && $inv['DUE_DATE'] < $today_dt);
            $sc_map = ['Paid'=>'paid','Pending Payment'=>'pending','Overdue'=>'overdue'];
            $status_label = $is_overdue ? 'Overdue' : $inv['STATUS'];
            $sc = $is_overdue ? 'overdue' : ($sc_map[$inv['STATUS']] ?? 'submitted');
            $outstanding = $inv['TOTAL'] - ($inv['PAID_AMOUNT'] ?? 0);
        ?>
        <div class="inv-row">
            <div style="flex:1;min-width:0">
                <div style="display:flex;align-items:center;gap:.5rem;margin-bottom:.15rem">
                    <span class="ir-num">INV-<?= str_pad($inv['INVOICE_ID'], 4, '0', STR_PAD_LEFT) ?></span>
                    <span class="badge badge-<?= $sc ?>"><?= $status_label ?></span>
                </div>
                <div style="font-size:.78rem;color:var(--text2)"><?= htmlspecialchars($inv['COMPANY_NAME'] ?? '—') ?> · Fault #<?= $inv['REP_FAULT_ID'] ?></div>
                <div style="font-size:.72rem;color:var(--text2);margin-top:.1rem">Due: <?= date('d M Y', strtotime($inv['DUE_DATE'])) ?></div>
            </div>
            <div style="text-align:right;flex-shrink:0">
                <div style="font-size:.88rem;font-weight:700;color:var(--accent)">E<?= number_format($inv['TOTAL'], 2) ?></div>
                <?php if ($inv['STATUS'] !== 'Paid' && $outstanding > 0): ?>
                <div style="font-size:.72rem;color:var(--danger);margin-top:.1rem">E<?= number_format($outstanding, 2) ?> outstanding</div>
                <!-- Send Reminder mini form -->
                <form method="POST" style="margin-top:.35rem">
                    <input type="hidden" name="action" value="resend">
                    <input type="hidden" name="invoice_id" value="<?= $inv['INVOICE_ID'] ?>">
                    <button type="submit" class="send-btn" title="Send payment reminder to client">
                        <i class="ti ti-send"></i> Remind
                    </button>
                </form>
                <?php else: ?>
                <div style="font-size:.72rem;color:var(--success);margin-top:.1rem"><i class="ti ti-circle-check"></i> Paid</div>
                <?php endif; ?>
            </div>
        </div>
        <?php endwhile; ?>
        </div>

        <a href="acc_invoices.php" class="btn btn-secondary btn-sm" style="margin-top:1rem;width:100%;justify-content:center">
            <i class="ti ti-external-link"></i> View All Invoices
        </a>
        <?php endif; ?>
    </div>

    <!-- Workflow Reference Card -->
    <div class="card" style="border-color:rgba(240,165,0,.2)">
        <div class="card-title"><i class="ti ti-map" style="color:var(--accent)"></i> Your Role in the Workflow</div>
        <div style="display:flex;flex-direction:column;gap:.5rem">
            <?php
            $steps = [
                ['done',   'ti-check',         'Client approved work'],
                ['done',   'ti-bell',          'Accountant notified'],
                ['active', 'ti-file-text',     'Review quotation lines'],
                ['active', 'ti-send',          'Generate & send invoice'],
                ['next',   'ti-credit-card',   'Client makes payment'],
                ['next',   'ti-shield-check',  'Verify payment receipt'],
                ['next',   'ti-lock',          'Fault closed & archived'],
            ];
            foreach ($steps as [$state, $icon, $label]):
                $clr = $state === 'done' ? 'var(--success)' : ($state === 'active' ? 'var(--accent)' : 'var(--text2)');
                $bg  = $state === 'done' ? 'rgba(63,185,80,.1)' : ($state === 'active' ? 'rgba(240,165,0,.08)' : 'var(--surface2)');
                $bdr = $state === 'done' ? 'rgba(63,185,80,.2)' : ($state === 'active' ? 'rgba(240,165,0,.25)' : 'var(--border)');
            ?>
            <div style="display:flex;align-items:center;gap:.65rem;padding:.5rem .75rem;background:<?= $bg ?>;border:1px solid <?= $bdr ?>;border-radius:8px;font-size:.8rem">
                <i class="ti <?= $icon ?>" style="color:<?= $clr ?>;font-size:.9rem;flex-shrink:0"></i>
                <span style="color:<?= $state === 'next' ? 'var(--text2)' : 'var(--text)' ?>"><?= $label ?></span>
                <?php if ($state === 'active'): ?><span style="margin-left:auto;font-size:.67rem;color:var(--accent);font-weight:700;flex-shrink:0">← NOW</span><?php endif; ?>
            </div>
            <?php endforeach; ?>
        </div>
    </div>

</div>
</div>

<!-- Invoice Preview Modal -->
<div class="modal-overlay" id="preview-modal">
    <div class="modal-box">
        <div class="modal-head">
            <h2><i class="ti ti-file-text" style="color:var(--accent)"></i> Invoice Preview</h2>
            <button onclick="closePreview()" class="btn btn-secondary btn-sm"><i class="ti ti-x"></i> Close</button>
        </div>
        <div class="modal-body">
            <div class="inv-preview-wrap">
                <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:1rem;flex-wrap:wrap;gap:.75rem">
                    <div>
                        <div class="inv-brand">Busi<span>quip</span></div>
                        <div style="font-size:.78rem;color:var(--text2)">BUSIQUIP ESWATINI<br>finance@busiquip.com · Mbabane, Eswatini</div>
                    </div>
                    <div style="text-align:right">
                        <div style="font-size:1.1rem;font-weight:800;color:var(--text)" id="pv-inv-num">INV-0000</div>
                        <div style="font-size:.78rem;color:var(--text2);margin-top:.2rem">Date: <?= date('d M Y') ?></div>
                        <div style="font-size:.78rem;color:var(--text2)">Due: <span id="pv-due" style="color:var(--accent);font-weight:600">—</span></div>
                    </div>
                </div>

                <div style="display:inline-flex;align-items:center;gap:.4rem;background:rgba(63,185,80,.1);border:1px solid rgba(63,185,80,.25);color:var(--success);padding:.35rem .8rem;border-radius:99px;font-size:.75rem;font-weight:700;margin-bottom:1rem">
                    <i class="ti ti-shield-check"></i> Client Approved — Generating Invoice
                </div>

                <div class="inv-grid">
                    <div class="inv-party">
                        <div class="lbl">From</div>
                        <div class="nm">BUSIQUIP ESWATINI</div>
                        <div class="sub">Mbabane, Eswatini<br>finance@busiquip.com</div>
                    </div>
                    <div class="inv-party">
                        <div class="lbl">Bill To</div>
                        <div class="nm" id="pv-client">—</div>
                        <div class="sub" id="pv-contact">—</div>
                        <div class="sub">Fault Ref: <span id="pv-fault">—</span></div>
                    </div>
                </div>

                <div id="pv-lines" style="margin-bottom:1rem"></div>

                <div style="background:rgba(240,165,0,.07);border:1px solid rgba(240,165,0,.2);border-radius:8px;padding:.85rem 1rem;display:flex;justify-content:space-between;align-items:center">
                    <span style="font-size:.85rem;font-weight:700;color:var(--text2);text-transform:uppercase;letter-spacing:.06em">Total Due</span>
                    <span style="font-size:1.5rem;font-weight:800;color:var(--accent)" id="pv-total">E0.00</span>
                </div>

                <div style="margin-top:.85rem;padding:.65rem;background:var(--surface);border-radius:8px;font-size:.75rem;color:var(--text2);line-height:1.6">
                    <strong style="color:var(--text)">Payment Methods:</strong> Mobile Money · Bank Transfer · Card Transfer<br>
                    Late payments may attract a 1.5% monthly finance charge. Thank you for choosing BUSIQUIP ESWATINI.
                </div>
            </div>

            <div style="font-size:.8rem;color:var(--text2);text-align:center">
                <i class="ti ti-info-circle"></i> This is a preview. Use the <strong style="color:var(--text)">Generate Invoice & Notify Client</strong> button to finalise.
            </div>
        </div>
    </div>
</div>

<script>
// ── Card toggle ────────────────────────────────────────────────────────────────
function toggleCard(id) {
    const body = document.getElementById('acb-' + id);
    const chev = document.getElementById('chev-' + id);
    const card = document.getElementById('ac-' + id);
    const isOpen = body.classList.contains('open');

    // Close all others
    document.querySelectorAll('.ac-body').forEach(b => b.classList.remove('open'));
    document.querySelectorAll('.approved-card').forEach(c => c.classList.remove('selected'));
    document.querySelectorAll('[id^="chev-"]').forEach(c => { c.className = 'ti ti-chevron-down'; });

    if (!isOpen) {
        body.classList.add('open');
        card.classList.add('selected');
        chev.className = 'ti ti-chevron-up';
        card.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
}

// ── Invoice Preview Modal ──────────────────────────────────────────────────────
function openPreview(invoiceId, company, total, contact, faultId) {
    document.getElementById('pv-inv-num').textContent  = 'INV-' + String(invoiceId).padStart(4, '0');
    document.getElementById('pv-client').textContent   = company;
    document.getElementById('pv-contact').textContent  = contact || '—';
    document.getElementById('pv-fault').textContent    = '#' + faultId;
    document.getElementById('pv-total').textContent    = 'E' + parseFloat(total).toFixed(2);

    // Get due date from the card's form if set
    const dueInput = document.querySelector('#acb-' + invoiceId + ' input[name="due_date"]');
    if (dueInput && dueInput.value) {
        const d = new Date(dueInput.value);
        document.getElementById('pv-due').textContent = d.toLocaleDateString('en-GB', {day:'2-digit',month:'short',year:'numeric'});
    }

    // Build lines table from DOM
    const lineTable = document.querySelector('#acb-' + invoiceId + ' .line-mini');
    const pvLines   = document.getElementById('pv-lines');
    if (lineTable) {
        pvLines.innerHTML = lineTable.outerHTML;
        pvLines.querySelector('table').style.width = '100%';
    } else {
        pvLines.innerHTML = '<p style="color:var(--text2);font-size:.8rem;text-align:center">No line items available.</p>';
    }

    document.getElementById('preview-modal').classList.add('open');
    document.body.style.overflow = 'hidden';
}

function closePreview() {
    document.getElementById('preview-modal').classList.remove('open');
    document.body.style.overflow = '';
}

// Close modal on backdrop click
document.getElementById('preview-modal').addEventListener('click', function(e) {
    if (e.target === this) closePreview();
});

// ESC key
document.addEventListener('keydown', function(e) {
    if (e.key === 'Escape') closePreview();
});

// ── Auto-open card if there's only one ────────────────────────────────────────
document.addEventListener('DOMContentLoaded', function() {
    const cards = document.querySelectorAll('.approved-card');
    if (cards.length === 1) {
        const id = cards[0].id.replace('ac-', '');
        toggleCard(parseInt(id));
    }
});

<?php if ($success_msg): ?>
showToast('<?= addslashes($success_msg) ?>', 'success');
<?php endif; ?>
<?php if ($error_msg): ?>
showToast('<?= addslashes($error_msg) ?>', 'error');
<?php endif; ?>
</script>

<?php require_once '../../includes/acc_footer.php'; ?>


